### ISSUE TITLE
Empty files when trying to convert multiple .md files to html

### ISSUE THREAD

**Issue by dennyabrain** [cwjohan/markdown-to-html#14]

**Comment by cwjohan** [comment]
Denny, I think it has never been tested this way. Perhaps there is
something about the Markdown object that is not reusable.  The test of that
would be to move the "let md = new Markdown();" statement into your logic
loop so that it is created every time the loop cycles.  Seems a bit
inefficient, but worth a try.  Maybe the Markdown class needs some reset
function to set up its internal pointers for reuse.  It may already have
one.  I haven't looked at the code for a very long time now and don't
recall.

**Comment by dennyabrain** [comment]
hey,

thats exactly what solved the problem for me :)
i tried to delete the issue because I felt this wasn't really a problem with the library itself. I can add the text back if you want or feel free to delete the issue.

**Comment by cwjohan** [comment]
OK.  Great.  Thanks for letting me know.
