### ISSUE TITLE
Rate Limit Exceeded - can I just download the parser?  (REMOVE)

### ISSUE THREAD

**Issue by jonandrewdavis** [cwjohan/markdown-to-html#18]
Nevermind.

Please remove, I'm just going to avoid making 60 requests per hour.

**Comment by cwjohan** [comment]
Hi Jon,

I think that is something happening behind the scenes, not in my code but
in some previously existing code called by mine.  I wasn't even aware that
the code would go to a server to do any of the work. I thought it was
stand-alone code.  I'm disappointed that it accesses a server.  I would
rather that my code not stop working because some server is unhappy or has
a new API or maybe even is no longer online.

Sounds like the server will accept more API calls on an authenticated
connection, but I don't make any such connection in my code.

Sorry for the inconvenience, but I can't help in this case.

Cheers,
Craig
