### ISSUE TITLE
Line Breaks Misread as BR instead of Continuing the Paragraph

### ISSUE THREAD

**Issue by rwxrob** [cwjohan/markdown-to-html#27]
https://github.github.com/gfm/#paragraphs

**Comment by cwjohan** [comment]
Rob, could you please give me more detail regarding where you see this.
Many things would look wrong and would have been wrong for a very long time
if this problem is more than some edge case.  For example, are you running
the command line utility?  On which platform are you running?  What is the
input you are submitting (just a small sample)?  Certainly, no code has
been put in markdown-to-html to explicitly and purposely treat single line
breaks as new paragraphs.

**Comment by cwjohan** [comment]
In the test directory, the very first test in test.md tests exactly this
case: that a single line break does not generate <p>.  See
github-markdown-ref.html and markdown-ref.html for example output based on
test.md as input.

**Comment by rwxrob** [comment]
​Sorry Craig, I've found pandoc does exactly what is expected (and faster).
I've moved on.​



*“Mr. Rob” Muhlestein*
*/^(Founder|Facilitator|Janitor|C\w\w?O)$/*
Content and community provide opportunity
SkilStak Coding Arts <https://skilstak.io>
rob@skilstak.com
704-310-6778
robs.io

**Comment by cwjohan** [comment]
I responded within one hour with some counter evidence and there is no follow up info from the person who reported the problem.  Closing this issue.

**Comment by rwxrob** [comment]
Oh it's broken, you will just need to confirm it yourself.



*“Mr. Rob” Muhlestein*
*/^(Founder|Facilitator|Janitor|C\w\w?O)$/*
Content and community provide opportunity
SkilStak Coding Arts <https://skilstak.io>
rob@skilstak.com
704-310-6778
robs.io
